os:
  - linux

language: php

php:
  - '7.1'

addons:
  postgresql: "9.5"

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - cp .env.travis .env
  - psql -c 'create database ezcon;' -U postgres
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install


script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: ezcon-api